# Jason Ivey SID: 800696866 - Jiveyguy@nmsu.edu

# dP         .d888888   888888ba  d8888b. 
# 88        d8'    88   88    `8b     `88 
# 88        88aaaaa88a a88aaaa8P'  aaad8' 
# 88        88     88   88   `8b.     `88 
# 88        88     88   88    .88     .88 
# 88888888P 88     88   88888888P d88888P 
# Sep 12th 2022                                        
                                        
# all rule, default when running "make" in this dir
all: lab3

# lex gen rule
lab3: symtable.c symtable.h
	gcc -o lab3 symtable.c

# run:
# 	./lab2_1 < comment.tst